///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using System.Windows.Forms;
using WinForms = System.Windows.Forms;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;
using Button = Ranorex.Button;
using Ranorex.Core.Data;
using System.Threading;

namespace TestCase
{
    public partial class Recording1
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        /// 
        private Ranorex.Core.Data.DataCache Data;
        private bool isFirstStart = false;


        //private Adapter txtRepeat;
        //private Ranorex.Location Lo_txtRepeat;
        //private Rectangle Lo_txtRepeat;
        //private Adapter textBoxMaskBox;
        //private Adapter txtMorning;
        //private Adapter txtAfternoon;
        //private Adapter txtLunch;
        //private Adapter txtEvening;
        //private Adapter txtQty;
        //private Adapter Table;
        //private Adapter btnThemthuoc;


        private Adapter richEditControl1;
        //private Adapter tableChiDinh;
        //private Adapter btnSaveClinic;
        private Point btnSaveClinic;
        //Ranorex.Button btnPrintClinic;
        private Point btnPrintClinic;
        //Ranorex.Control txtRepeat;
        //Ranorex.Control textBoxMaskBox;
        //Ranorex.Control txtMorning;
        //Ranorex.Control txtAfternoon;
        //Ranorex.Control txtLunch;
        //Ranorex.Control txtEvening;
        //Ranorex.Control txtQty;
        Ranorex.Table Table;
        Ranorex.Table tableChiDinh;
        private Point btnThemthuoc;
        private Point Lo_btnThemthuoc;

        Ranorex.Button chỉĐịnhDịchVụF5;
        Ranorex.Button khamBệnhF1;
        Ranorex.Button keĐơnF6;
        Element element;

        Point buttonLưu;
        Point buttonIn;
        Point closefrmDetail;
        Point btnINPHIEU;
        Point btnPrintSchedule;

        Point INBANGKE;
        Point btnPopUpSchedule;
        Point btnSaveSchedule;
        Point[] elemchidinh = new Point[3];

        private void Init()
        {
            Data = DataSources.Get("RXCase");
            Ranorex.Controls.ProgressForm.Hide();




            //Host.Local.RunApplication("D:\\@BV110\\Launcher.exe");
        }

        public void DialogPopup()
        {
            if (repo.XacNhận.SelfInfo.Exists(0)) //check exist
            {
                var buttonCo = repo.XacNhận.ButtonCo;
                Report.Warn("Warning!");
                Report.Screenshot();
                buttonCo.Click();


            }

            if (repo.CảnhBao.SelfInfo.Exists(0))//check exist
            {
                var buttonOK = repo.CảnhBao.ButtonOK;
                Report.Warn("Warning!");
                Report.Screenshot();
                buttonOK.Click();
            }
            if (repo.FormLỗi.SelfInfo.Exists(0))//check exist
            {
                var buttonOK1 = repo.FormLỗi.ButtonOK;
                Report.Error("This step is error!");
                Report.Screenshot();
                buttonOK1.Click();
            }
        }


        public void FlowInputRx(RepoItemInfo textInfo)
        {
            var DateEditKB = repo.FrmMain.List25ThangMươiMot1944;

            DateEditKB.DoubleClick();
            DateEditKB.PressKeys("05092018", 200);

            int elementofTrangThai;
            var tabledsBN = repo.FrmMain.Table1;
            var buttonLoc = repo.FrmMain.ButtonLọc1;


            buttonLoc.Click();



            elementofTrangThai = findElementColNameTableControl(tabledsBN, 0, "Trạng thái");


            if (tabledsBN.Children[1].Children.Count != 0)
            {
                for (int i = 1; i <= tabledsBN.Children[1].Children.Count; i++)
                {
                    string obj;

                    obj = ((Ranorex.Plugin.MsaaFlavorElement)tabledsBN.Children[1].Children[i].Children[elementofTrangThai].Element.FlavorElement).Value;


                    if (obj == "Đang khám")
                    {
                        tabledsBN.Children[1].Children[i].DoubleClick();



                        chỉĐịnhDịchVụF5 = repo.FrmNewDetail.ChỉĐịnhDịchVụF5;
                        khamBệnhF1 = repo.FrmNewDetail.KhamBệnhF1;
                        keĐơnF6 = repo.FrmNewDetail.KeĐơnF6;


                        //var keĐơnF6  = repo.FrmNewDetail.KeĐơnF6;


                        #region SaveReason
                        if (!khamBệnhF1.Pressed)
                        {
                            khamBệnhF1.Click();

                            #region init control
                            richEditControl1 = repo.FrmNewDetail.RichEditControl1;
                            #endregion


                            Mouse.Click(richEditControl1.ScreenRectangle.Location);
                            //richEditControl1.PressKeys("Reason", 0);
                            Keyboard.EscapeSequence("Reason");
                            //                     var txtICDChinh = repo.FrmNewDetail.TextMaskBox;
                            //                     txtICDChinh.PressKeys("K51",0);
                            //                     Keyboard.Down(Keys.Tab);
                            //                     Keyboard.Down(Keys.Tab);
                            //                     var txtICDPhu = repo.FrmNewDetail.MainPanel.TextMaskBox1;
                            //                     txtICDChinh.PressKeys("K52",0);
                            //Keyboard.Down(Keys.Tab);
                            //                     Keyboard.Down(Keys.Tab);
                        }
                        #endregion



                        #region SaveClinical


                        if (!chỉĐịnhDịchVụF5.Pressed)
                        {
                            chỉĐịnhDịchVụF5.Click();
                            if (!isFirstStart)
                            {
                                btnSaveClinic = repo.FrmNewDetail.MainPanel.ButtonLưu1.ScreenRectangle.Location;
                                btnPrintClinic = repo.FrmNewDetail.MainPanel.InChỉĐịnh.ScreenRectangle.Location;
                                tableChiDinh = repo.FrmNewDetail.MainPanel.Table1;
                            }


                            for (int elemclinic = 0; elemclinic < 3; elemclinic++)
                            {
                                if (!isFirstStart)
                                {
                                    elemchidinh[elemclinic] = tableChiDinh.Children[1].Children[elemclinic].ScreenRectangle.Location;
                                }
                                //tableChiDinh.Children[1].Children[elemclinic].DoubleClick();

                                Mouse.DoubleClick(elemchidinh[elemclinic]);
                                Report.Log(ReportLevel.Info, "Select clinic");
                            }

                            Mouse.Click(btnSaveClinic);
                            Thread.Sleep(2000);
                            //btnSaveClinic.Click();


                            DialogPopup();
                            //Thread.Sleep(Convert.ToInt32(repo.StartFoxitPhantomPDF.SearchTimeout));

                            //btnPrintClinic.Click();
                            Mouse.Click(btnPrintClinic);
                            if (repo.Shell1.SelfInfo.Exists(2000))//check exist
                            {
                                Report.Error("error when printed InPhieuChiDInh!");
                                Report.Screenshot();
                                Keyboard.Down(Keys.Enter);
                            }
                            //Thread.Sleep(5000);
                            repo.StartFoxitPhantomPDF.SelfInfo.WaitForExists(5000);





                        }
                        #endregion


                        #region SaveDiagnosis
                        if (!khamBệnhF1.Pressed)
                        {
                            khamBệnhF1.Click();
                            var txtICDChinh = repo.FrmNewDetail.MainPanel.TextMaskBox1;
                            if (((Ranorex.Plugin.WinFormsFlavorElement)txtICDChinh.Element.FlavorElement).Text.Trim() == "")
                            {
                                txtICDChinh.PressKeys("K51", 0);
                                Keyboard.Down(Keys.Tab);
                                Keyboard.Down(Keys.Tab);
                                Report.Log(ReportLevel.Info, "Keyboard", "MainICD: " + "K51", repo.FrmNewDetail.MainPanel.TextMaskBox1Info, new RecordItemIndex(1));
                            }
                            var txtICDPhu = repo.FrmNewDetail.MainPanel.TextMaskBox;
                            if (((Ranorex.Plugin.WinFormsFlavorElement)txtICDPhu.Element.FlavorElement).Text.Trim() == "")
                            {
                                txtICDPhu.PressKeys("K52", 0);
                                Keyboard.Down(Keys.Tab);
                                Keyboard.Down(Keys.Tab);
                                Report.Log(ReportLevel.Info, "Keyboard", "MainICD: " + "K52", repo.FrmNewDetail.MainPanel.TextMaskBoxInfo, new RecordItemIndex(1));
                            }

                        }
                        #endregion




                        #region SaveRX


                        if (keĐơnF6.Pressed == false)
                        {
                            //Keyboard.Down(Keys.F6);
                            keĐơnF6.Click();
                            #region init control


                            var txtRepeat = repo.FrmNewDetail.TableLayoutPanel1.txtRepeat;
                            element = txtRepeat.Element;


                            var textBoxMaskBox = repo.FrmNewDetail.TableLayoutPanel1.searchLookupProduct;
                            var txtMorning = repo.FrmNewDetail.TableLayoutPanel1.txtMorning;
                            var txtAfternoon = repo.FrmNewDetail.TableLayoutPanel1.txtAfternoon;
                            var txtLunch = repo.FrmNewDetail.TableLayoutPanel1.txtLunch;
                            var txtEvening = repo.FrmNewDetail.TableLayoutPanel1.txtEvening;
                            var txtQty = repo.FrmNewDetail.TableLayoutPanel1.txtQty;

                            #endregion






                            Table = repo.FrmNewDetail.Table;
                            for (int j = 0; j <= Data.Rows.Count - 1; j++)
                            {


                                var row = Data.Rows[j];
                                if (Table.Children[1].Children.Count == 0 && ((Ranorex.Plugin.WinFormsFlavorElement)txtRepeat.Element.FlavorElement).Text.Trim() == "")
                                {
                                    txtRepeat.PressKeys(row.Values[1].ToString());
                                }
                                else
                                {
                                    //do nothing
                                }

                                textBoxMaskBox.PressKeys(row.Values[0].ToString(), 0);
                                Report.Log(ReportLevel.Info, "Keyboard", "Product is input " + row.Values[0].ToString(), repo.FrmNewDetail.TableLayoutPanel1.searchLookupProductInfo, new RecordItemIndex(j));
                                Keyboard.Down(Keys.Enter);
                                Report.Log(ReportLevel.Info, "Press enter");
                                //var tenSPRow0 = repo.Shell1.TenSPRow0;
                                //tenSPRow0.Click();
                                txtMorning.PressKeys(row.Values[2].ToString(), 0);
                                Report.Log(ReportLevel.Info, "Keyboard", "Morning is input " + row.Values[2].ToString(), repo.FrmNewDetail.TableLayoutPanel1.txtMorningInfo, new RecordItemIndex(j));
                                txtAfternoon.PressKeys(row.Values[4].ToString(), 0);
                                Report.Log(ReportLevel.Info, "Keyboard", "Afternoon is input " + row.Values[4].ToString(), repo.FrmNewDetail.TableLayoutPanel1.txtAfternoonInfo, new RecordItemIndex(j));
                                txtLunch.PressKeys(row.Values[3].ToString(), 0);
                                Report.Log(ReportLevel.Info, "Keyboard", "Lunch is input " + row.Values[3].ToString(), repo.FrmNewDetail.TableLayoutPanel1.txtLunchInfo, new RecordItemIndex(j));
                                txtEvening.PressKeys(row.Values[5].ToString(), 0);
                                Report.Log(ReportLevel.Info, "Keyboard", "Evening is input " + row.Values[5].ToString(), repo.FrmNewDetail.TableLayoutPanel1.txtEveningInfo, new RecordItemIndex(j));
                                txtQty.PressKeys("2", 0);
                                Report.Log(ReportLevel.Info, "Keyboard", "Quanity is input '2'.", repo.FrmNewDetail.TableLayoutPanel1.txtQtyInfo, new RecordItemIndex(j));

                                Mouseclick(j);
                            }

                        }
                        #endregion





                    }



                }
            }






        }

        private int findElementColNameTableControl(Ranorex.Table table, int element, string ColumnName)
        {
            for (int i = 1; i <= table.Children[1].Children.Count; i++)
            {
                for (int t = 0; t <= table.Children[1].Children[i].Children.Count; t++)
                {
                    if (((Ranorex.Plugin.MsaaFlavorElement)table.Children[1].Children[i].Children[t].Element.FlavorElement).Name.Replace(" row 0", "") == ColumnName)
                    {
                        element = t;
                        break;
                    }
                }
                break;
            }

            return element;
        }


        public void Mouseclick(int total)
        {

            if (!isFirstStart)
            {
                Lo_btnThemthuoc = repo.FrmNewDetail.MainPanel.ThemThuốc.ScreenRectangle.Location;
                //Lo_btnThemthuoc = btnThemthuoc.ScreenRectangle.Location;

            }



            Mouse.Click(Lo_btnThemthuoc);
            //btnThemthuoc.Click();
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'buttonInfo' at Center.", button);
            //button.FindAdapter<Button>().Click();


            //var cảnhBao = repo.CảnhBao;
            //var formLỗi = repo.FormLỗi;
            //var xacNhận = repo.XacNhận;


            DialogPopup();



            if (total == Data.Rows.Count - 1)
            {

                if (!isFirstStart)
                {
                    buttonLưu = repo.FrmNewDetail.ButtonLưu.ScreenRectangle.Location;
                    buttonIn = repo.FrmNewDetail.ButtonIn.ScreenRectangle.Location;
                    closefrmDetail = repo.FrmNewDetail.Close.ScreenRectangle.Location;
                    btnINPHIEU = repo.FrmNewDetail.INPHIẾU.ScreenRectangle.Location;
                    btnPrintSchedule = repo.FrmNewDetail.MainPanel.InGiấyHẹnTaiKham.ScreenRectangle.Location;

                }


                //buttonLưu.Click();
                Mouse.Click(buttonLưu);

                Thread.Sleep(4000);
                SaveSchedule();

                Thread.Sleep(1500);
                //btnPrintSchedule.Click();
                Mouse.Click(btnPrintSchedule);
                if (repo.Shell1.SelfInfo.Exists(500))//check exist
                {
                    Report.Error("error when printed INGiayHenTaiKHam!");
                    Report.Screenshot();
                    Keyboard.Down(Keys.Enter);
                }


                repo.StartFoxitPhantomPDF.SelfInfo.WaitForExists(5000);
                //Thread.Sleep(Convert.ToInt32(repo.StartFoxitPhantomPDF.SearchTimeout));
                //Thread.Sleep(6000);
                //buttonIn.Click();
                Mouse.Click(buttonIn);
                if (repo.Shell1.SelfInfo.Exists(500))//check exist
                {
                    Report.Error("error when printed INDonThuoc!");
                    Report.Screenshot();
                    Keyboard.Down(Keys.Enter);
                }
                else
                {
                    Report.Success("Passed!");
                    Report.Screenshot();

                }


                repo.StartFoxitPhantomPDF.SelfInfo.WaitForExists(5000);
                //Thread.Sleep(Convert.ToInt32(repo.StartFoxitPhantomPDF.SearchTimeout));

                //Thread.Sleep(6000);
                //btnINPHIEU.MoveTo();
                Mouse.MoveTo(btnINPHIEU);
                Thread.Sleep(100);
                if (!isFirstStart)
                { INBANGKE = repo.Shell1.INBẢNGKE.ScreenRectangle.Location; }

                //INBANGKE.Click();
                Mouse.Click(INBANGKE);
                if (repo.Shell1.SelfInfo.Exists(500))//check exist
                {
                    Report.Error("error when printed InBANGKE!");
                    Report.Screenshot();
                    Keyboard.Down(Keys.Enter);
                }
                else
                {
                    Report.Success("Passed!");
                    Report.Screenshot();

                }
                repo.StartFoxitPhantomPDF.SelfInfo.WaitForExists(5000);

                //Thread.Sleep(Convert.ToInt32(repo.StartFoxitPhantomPDF.SearchTimeout));
                //Thread.Sleep(6000);

                //closefrmDetail.Click();
                Mouse.Click(closefrmDetail);
                isFirstStart = true;



            }



        }

        public void SaveSchedule()
        {

            if (!isFirstStart)
            {
                btnPopUpSchedule = repo.FrmNewDetail.MainPanel.ĐặtLịch.ScreenRectangle.Location;

            }
            Mouse.Click(btnPopUpSchedule);

            //btnPopUpSchedule.Click();


            if (!isFirstStart)
                btnSaveSchedule = repo.FrmPatientScheduledVisits.ButtonLưu.ScreenRectangle.Location;
            //btnSaveSchedule.Click();
            Mouse.Click(btnSaveSchedule);
            //DialogPopup();
            //if(repo.FrmPatientScheduledVisits.SelfInfo.Exists(0))
            //{
            //	var close = repo.FrmPatientScheduledVisits.Close;
            //    close.Click();
            //}


        }



    }
}
